### ISSUE TITLE
[Question] How I can make a same Menu on the next page ?

### ISSUE THREAD

**Issue by BogusCurry** [blitze/phpBB-ext-sitemaker#10]
Hello ;D
How I can make the same Menu on the next page, example the menu on the startpage and they same on the gallery site ? I see that I can copy the blocks, but how I make I this ?

Thanks for your support ;D

Greetings

Bogus

**Comment by blitze** [comment]
You can set your layout as the default layout and it will be repeated on all other pages that you have not added blocks to. You can also copy a layout to another page.
For the menu specifically, you can just add a menu block, then select the same menu as you did on the  other page. Hope that makes sense.
