### ISSUE TITLE
Disable Extension

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#13]
When you disable extention you still have a Category left should it not delete that also?

![cd](https://cloud.githubusercontent.com/assets/17803396/13728765/b183823c-e922-11e5-8b57-86e7ffa2bddc.png)

**Comment by blitze** [comment]
This is intentional. The reason being that there is another extension that I'm working on that creates forums and topics and I don't want all of that deleted if they choose to uninstall the extension.
