### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#16]
Have add 3 Featured Member block 2 on left and 1 on right and when i try change settings to Featured member on the right one that don't work...
![2016-03-15_080419](https://cloud.githubusercontent.com/assets/17803396/13770140/3c14ee8c-ea85-11e5-9bd9-eb6e7a9d5509.png)

version 2.0.3

**Comment by blitze** [comment]
Unchecked the "Update blocks with similar settings" option ams try again, them let me know. May be i should have this box unchecked by default

**Comment by Sippan-66** [comment]
Weird when i set Featured Member ...1 time it shows my name when i have set id and save
when i exit mode then it dissepear and tells me No data to display

**Comment by Sippan-66** [comment]
images to see what
![11](https://cloud.githubusercontent.com/assets/17803396/13785277/40f4fbc4-ead3-11e5-8ae6-8af1b600c8aa.png)
![22](https://cloud.githubusercontent.com/assets/17803396/13785280/43a72ff4-ead3-11e5-8eb6-32b7205a63a7.png)

**Comment by blitze** [comment]
So let me understand the sequence of events: you add a featured member block and set it to show Top Posters, then you add a second Featured member block showing recent members (by default,  i presume). You then add a third Featured member block and it works initially. You edit it and add a user ID and save it and it returns with "no data to display". Is this correct? If so,  what is the user ID you entered? Does the user with that ID exist?

**Comment by Sippan-66** [comment]
exactly like that and i put in ID 2 and thats me :-)

**Comment by blitze** [comment]
Issue is resolved
