### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#18]
Hi and featured members works great GJ..Now next
dont know if i understand Menu block but when i move it over from blocks edit mode and put it on right side bar so are there not any settings to choose
![44](https://cloud.githubusercontent.com/assets/17803396/13804061/03f8a262-eb4a-11e5-8874-b8e903bbaf7d.png)
and when i save and exit edit menu it dissepear also and thats same for Birthday block,Poll block,Attachments block.Links block,Custom block...all blocks dissepear after exit edit mod on the below image
![55](https://cloud.githubusercontent.com/assets/17803396/13804308/1ec75348-eb4c-11e5-8608-c4188d6b7ef3.png)
![66](https://cloud.githubusercontent.com/assets/17803396/13804691/67d069f0-eb4f-11e5-89df-1778cf7ee5da.png)
Seems if they have some info inside they stay :-) did test on your demo site and did get some info how Menu works...Maybe it should be so?

**Comment by blitze** [comment]
You are correct. For most blocks, and that includes all the ones that you mentioned, if there is nothing to display, the block is not shown, unless you are in edit mode.

**Comment by Sippan-66** [comment]
ok then its ok...
