### ISSUE TITLE
Width on Block

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#20]
Is it possible in setting on each block set width?
Like it's now is they realy big

**Comment by blitze** [comment]
Currently that is not an option. However, you can add a CSS class to any block. The current idea is that a block will fill the space that's given to it.  So not all blocks are suitable for display on large spaces

**Comment by Sippan-66** [comment]
ok then i know...

**Comment by Sippan-66** [comment]
I take it here .-) Featured Member is weird it don't show latest member just site admin and thats same on demo site and my test site

**Comment by Sippan-66** [comment]
Can you give me a example with css class i can set in the block have try alot classes but no changes

**Comment by blitze** [comment]
It can be any class. So you will need to define your own class. This may require modifying the phpbb style that you are using.

BTW, I think we should use the phpbb forum for questions and feature requests that way others can benefit from the discussion, but post any bugs here.

**Comment by Sippan-66** [comment]
ok sorry

**Comment by blitze** [comment]
Oh no need. I am the one who suggested you post here to begin with. I only suggested posting on the forum so that the extension us talked about and so that i can gauge what the majority of people would want as far as features are concerned

**Comment by blitze** [comment]
I will keep an open mind to this if more people ask for it. Closing for now
