### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#21]
When I minimize page and click the drop-down sign
and returns to normal mode will end up the block at the top
![222](https://cloud.githubusercontent.com/assets/17803396/13821160/baeee304-eba0-11e5-8d98-9f41eb728b77.png)
![3333](https://cloud.githubusercontent.com/assets/17803396/13821161/bd3456b2-eba0-11e5-9280-7df307d79d53.png)
![66](https://cloud.githubusercontent.com/assets/17803396/13821163/bf17f74a-eba0-11e5-9e43-b6f25362905a.png)

**Comment by blitze** [comment]
Yeah I've seen this but not sure i want to fix or that i can fix. Mainly because the issue is resolved if you refresh the page. I also don't expect that someone will be resizing the browser that much

**Comment by Sippan-66** [comment]
ok...

**Comment by blitze** [comment]
Do you think it is a problem? I can give it a second look and see if I can fix

**Comment by Sippan-66** [comment]
No its not a problem for me just it will look more pro :-) if it doesen't ......if some resize and dont know looks it terrible lol if it's easy to fix why not  :-)

**Comment by blitze** [comment]
ok, I will take another look... will let you know

thanks

**Comment by Sippan-66** [comment]
:+1:

**Comment by blitze** [comment]
Ok resolved this issue. Thanks for pushing me to do the very best possible. I did not have the strength to go after this issue. I appreciate all the testing you've been doing, I really do.

**Comment by Sippan-66** [comment]
Great good job Will test IT later 😀

**Comment by Sippan-66** [comment]
Woow did test it and now we talk hehe GJ
