### ISSUE TITLE
block

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#23]
Hi again!
attachment block had been nice with space after image so the text not comes direct
![11](https://cloud.githubusercontent.com/assets/17803396/13905511/ec952f66-eec1-11e5-9340-56d53e901fd8.png)

**Comment by blitze** [comment]
Fixed

**Comment by Sippan-66** [comment]
Now its realy weird
![kk](https://cloud.githubusercontent.com/assets/17803396/13907615/71221b56-eef2-11e5-9328-581cafe09c10.png)

**Comment by blitze** [comment]
I don't understand. I don't see the problem from the screenshot

**Comment by Sippan-66** [comment]
look at first post so will you see diffrents

**Comment by blitze** [comment]
So the 2nd one is better right? Take a look at the demo site: http://phpbb-sitemaker.website/demo/index.php

**Comment by Sippan-66** [comment]
demo site looks good but on my test site it dont i will try upload a new images on test site brb

**Comment by Sippan-66** [comment]
No looks like shit on my test site its a hugh image not like it is on demo site

**Comment by blitze** [comment]
post same image on demo site let me see please

**Comment by blitze** [comment]
By the way, have you tried clearing cache?

**Comment by Sippan-66** [comment]
hehe darn i did send 2 you need to approve it
and i will test clearing cache

**Comment by Sippan-66** [comment]
same results hugh image in block

**Comment by blitze** [comment]
Ok I have approved them. Please take a look and see if the problem exists on the demo site

**Comment by Sippan-66** [comment]
weird there it looks good

**Comment by blitze** [comment]
ok here is a question. Where are you placing the block? Take a look at the demo site again

**Comment by Sippan-66** [comment]
take a look lol
![mm](https://cloud.githubusercontent.com/assets/17803396/13908007/8d9e4f90-eefa-11e5-8d9a-119a607fcbe3.png)

**Comment by Sippan-66** [comment]
is it same file on 3.2?

**Comment by blitze** [comment]
Is this the same file you posted on the demo site? The demo site is running phpBB 3.1.8. I will add to 3.2 and see what it looks like

**Comment by Sippan-66** [comment]
ok but when you make site half and click on the sign to expand blocks it looks weird on demo site ...that we did talk last time about and you had a hell to fix ....so have you update that to lates?

**Comment by Sippan-66** [comment]
dam clock is much i will test it tomorrow i did attachement on my 3.1.7 forum and it looks good its on 3.2 it fails good luck and hope you fix it hehe

**Comment by Sippan-66** [comment]
its weird today it looks ok with that attachment block...on 3.2 system and i did purge data so many times
yesterday and to day i start up and all looks ok....

**Comment by Sippan-66** [comment]
Now i know the issue google chrome shows correct and firefox shows big images

**Comment by Sippan-66** [comment]
Hi do you have any solution to that?

**Comment by blitze** [comment]
I was finally able to reproduce this. I'm working on it now

**Comment by blitze** [comment]
This issue is resolved.

**Comment by Sippan-66** [comment]
blank page after update
