### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#24]
When i have put up 2 blocks beside each other like this in center

![2blocks](https://cloud.githubusercontent.com/assets/17803396/13977722/c31efe94-f0cb-11e5-95b8-5fc42b04edf1.png)
When i should edit the sec block do i get this

![missing](https://cloud.githubusercontent.com/assets/17803396/13977740/d73552f2-f0cb-11e5-9564-f54102ed8782.png)
can't even find that file exceptions.php
Have try diffrent setups and with same results
but if i edit them on side bar and then move them to center it works

**Comment by blitze** [comment]
Ok i know what's going on there, i will fix later today. At work now

**Comment by blitze** [comment]
This is now resolved
