### ISSUE TITLE
upload images

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#27]
When i upload an image it get hugh like the smileys did b4 you changed

**Comment by blitze** [comment]
Can you explain this a little more? I need the steps you are taking before encountering this. 

Thanks

**Comment by Sippan-66** [comment]
You can Close it.... after i did unactivate sitemaker and reactivate it and Clean purge so can't i make it happen again

**Comment by blitze** [comment]
Ok cool
