### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#28]
Catchable fatal error: Argument 4 passed to phpbb\template\twig\environment::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, string given in /opt/lampp/htdocs/forum/phpbb/template/twig/environment.php on line 59

**Comment by blitze** [comment]
what version of phpBB are you running?

**Comment by Sippan-66** [comment]
3.2 and it don't help

**Comment by blitze** [comment]
you are on phpBB-3.2.0-b2. I have been coding against the master branch which is phpBB 3.3. I will update

**Comment by blitze** [comment]
So here's the thing... I will not fix this one. What I will do is raise the minimum phpBB version to phpBB 3.2.0-RC1. The dependencies for twig environment are the same on the 3.2.x branch and the master branch. Only the prep-release-3.2.0-b2 branch (which is what you are running) has a different dependency. A new branch (prep-release-3.2.0-RC1) was just created a few days ago, which should fix this issue. So I'll say just wait for phpbb 3.2.0-RC1 to be released

**Comment by Sippan-66** [comment]
ok..thx for info...do you have a clue when it will be released?

**Comment by blitze** [comment]
No idea, but the fact that they've created that branch means we're not too far off. If this is an issue for you, I can give you steps to fix manually. Let me know

**Comment by Sippan-66** [comment]
not need i wait  :-) thx any way

**Comment by CaldazarSoulraven** [comment]
I cant seem to get it to work correctly.... ACP wont allow me to create new menu items (Tried in Google Chrome and Maxthon) not sure how to install the "vendors" since the files appear to be missing?

**Comment by blitze** [comment]
Hi CaldazarSoulraven, thanks for your interest. I'm assuming that you are working with the develop branch which is for the phpBB 3.2 branch. I am also assuming that you downloaded your copy directly from github, which is why the vendors are not included. 
To get a working build, please go here: http://phpbb-sitemaker.website 

Thanks

**Comment by CaldazarSoulraven** [comment]
You would be correct, will try it the correct way now, thank you.

**Comment by CaldazarSoulraven** [comment]
Hmm, I appear to have the same issue still, the Add Menu button on ACP page does nothing when clicked. I deleted sitedata, deleted all old files, before uploading the one form your website and enabling it.

**Comment by blitze** [comment]
Clear the cache in acp

**Comment by blitze** [comment]
Is this still an issue? Can I close this?

**Comment by CaldazarSoulraven** [comment]
yeah believe so, i closed my host and installed server on my own system to
save a bit of money, so im in the process of setting that up atm
