### ISSUE TITLE
Block witdh

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#29]
Long time no see i did test your sitemaker dev and it looks good so far
BUT full witdh on my board and sitemaker on that looks awful the block must be atleast 400 px if not more
please make a settings for that in acp

**Comment by blitze** [comment]
It's so great to here from you. It's been quite some time now. Could you tell me what style you're using so I can try to reproduce the problem? Or provide a screenshot so I have something to work off of. Any idea how you think this setting would work?

Thanks

**Comment by Sippan-66** [comment]
HI ...
wrap prosilver 100% 
even with orginal size its to big
In acp should you have settings to set width or in each block i have try set
width: 200px; but that dont work in blocks
Thas the only thing that bothers me or so does it looks great you have done some great job

**Comment by blitze** [comment]
So the extension uses a % width grid for the layout instead of a fixed width. The way I see it, the problem is with styles that are set to display at full width knowing that these days people use all kinds of devices: from cell phones to very high resolution large screens. If I set the width to 200px then you also have this very large main section. I'm not sure how to solve for this one. I am open to ideas though.

**Comment by Sippan-66** [comment]
just have it like you have but make a ACP setting there you can make your own choose how width the block should be...so is it up to each one if they want to change block width
make just a test if that can be done more than happy to test that for ya... :-)

**Comment by blitze** [comment]
I can't tackle this right now. I will soon provide instructions on how you can build the css for your own style, which really has always been the plan. What I have is for prosilver. I will revisit this in a bit. Right now the priority is to submit the 3.2 version for approval.

**Comment by blitze** [comment]
As of 3.2.1-RC1, I have added a holy grail layout option i.e. two fixed width sidebars and a middle section that expands to fill the available space. I think this should address your issue here
