### ISSUE TITLE
Removing/deleting blocks

### ISSUE THREAD

**Issue by maxwellqc13** [blitze/phpBB-ext-sitemaker#31]
Question on changing or removing blocks.   I am using mostly custom blocks and then use the edit option and add code under source tab.   This works well but I need to change the content or remove blocks sometimes and can't figure out how to do this.

The little gear and delete in the top right corner does not exist once the layout is saved so my only option is to delete all the blocks and recreate the entire page.

Thanks for all the work you have done on this extension  it is a great addition to any site.

**Comment by blitze** [comment]
Thanks for reaching out. This was a variable scope issue with Twig (my fault). I have since fixed the issue. Please download the latest release here: http://phpbb-sitemaker.website/index.php
