### ISSUE TITLE
Fatal Error after Upgrade to phpBB 3.2.1

### ISSUE THREAD

**Issue by area57** [blitze/phpBB-ext-sitemaker#36]
Hi,

i get an Error after Upgrading to phpBB 3.2.1 if i have enabled SiteMaker,
it could be this funcition:

```
protected function getBlitze_Sitemaker_Template_Twig_EnvironmentService()
    {
        $this->services['blitze.sitemaker.template.twig.environment'] = $instance = new \phpbb\template\twig\environment($this->get('config'), $this->get('filesystem'), $this->get('path_helper'), './cache/production/twig/', $this->get('ext.manager'), $this->get('blitze.sitemaker.template.twig.loader'), array());

        $instance->setLexer($this->get('template.twig.lexer'));

        return $instance;
    }
```

it is refered in apache error log under:

`PHP Catchable fatal error:  Argument 7 passed to phpbb\\template\\twig\\environment::__construct          () must implement interface phpbb\\event\\dispatcher_interface, array given, called in /webserver/cache/production/container_4335734bbdd20f586549a504dff5f80c.php on line           1440 and defined in /home/osmc/webserver/phpbb/template/twig/environment.php on line 62`

the error is persistent no matter if i delete the cache or not

**Comment by blitze** [comment]
Hi area57,
Thanks for reporting this issue. It has to do with a change in twig environment dependencies for phpBB 3.2.1. Please take a look at my reply here for options: https://www.phpbb.com/customise/db/extension/phpbb_sitemaker_2/support/topic/180081?p=575876#p575876
