### ISSUE TITLE
Site maker is renaming "board index" link at the top to "home"

### ISSUE THREAD

**Issue by Supermillhouse** [blitze/phpBB-ext-sitemaker#37]
Site maker is renaming "Board index" link at the top to "Home"
Sorry the image is so big :(
![untitled1](https://user-images.githubusercontent.com/5963597/28920915-c3e370c2-784b-11e7-9b95-5a94ab473462.png)

**Comment by blitze** [comment]
Thanks for reporting this issue. The issue has been handled but will take some time for phpBB to approve
