### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by leschek** [blitze/phpBB-ext-sitemaker#5]
1. When I click on board index on the red sitemaker button I get the following error:
Fatal error: Class 'Urodoz\Truncate\TruncateService' not found in ...\ext\blitze\sitemaker\blocks\forum_topics.php on line 75

2. In ACP - Dashboard you use in those colored rectangles some language variables from core phpBB and they have wrong form of plural. I guess it would be better if you use your own language variables for it. Also all those information are on first page in ACP.

3. phpBB News block - I'm not sure what benefit it has for people who doesn't speak English as it's untranslatable.

**Comment by blitze** [comment]
Hello leschek,

Sorry for the late reply:

1. You need to run php composer.phar install to install dependencies

2. The dashboard is an idea that is not fully baked to be honest with you. I want to put some useful information there, that phpBB does not already provide. I also wanted to make it so other extensions that I write can add stuff on the dashboard. Please let me know if you have any ideas.

3. I see what you're saying about that content not being translatable, but phpBB provides this on their site without translation. I thought about making it so the user can input the title and the RSS feed to get news from but haven't gotten to it yet. Again, please let me know what you think here.

Thanks for your interest in this extension. Please keep your thoughts/feedback coming.

Regards,

Daniel

**Comment by leschek** [comment]
Thank you for answers.

1. I have no idea how to do that, so I will wait until everything is installed during installation of extension.

3. It would be nice to have option to disable such a block, because users who don't speak English will have no use for it.

**Comment by blitze** [comment]
I have gotten rid of the dashboard. It was not a fully baked idea and I'm not sure I would have had the time to do all the things I planned to do with it. So problem solved... in a way
