### ISSUE TITLE
Get error in "Recent Forum Topics"  if "Template = mini"

### ISSUE THREAD

**Issue by demonlibra** [blitze/phpBB-ext-sitemaker#50]
Good day.

If in block "Recent Forum Topics" change parameter "Template" to "mini" get this error:

`An exception has been thrown during the rendering of a template ("DateTime::__construct(): Failed to parse time string (Ср май 08, 2019 15:08) at position 0 (�): Unexpected character") in "blocks/forum_topics.html" at line 40.`
![error1](https://user-images.githubusercontent.com/39235959/57380810-5bd03580-71b2-11e9-9832-0fb3545cd2c5.png)

When trying to open a page get this error:
![error_3](https://user-images.githubusercontent.com/39235959/57438350-65a67700-724c-11e9-8930-50cb6f16dfa5.png)
The problem present only If set not english language. 

phpBB 3.2.7 (on older versions was the same problem)
PHP 7.1.11 and 7.1.21

SiteMaker 3.1.1 from https://www.phpbb.com/customise/db/extension/phpbb_sitemaker_2/
and
SiteMaker 3.2.0 from https://github.com/blitze/phpBB-ext-sitemaker/tree/release-3.2.0

Thanks for your titanic job.

**Comment by demonlibra** [comment]
After changed language to english in UCP the problem is gone.

If I change language to "russian" the problem comeback.
But if I change "My date format:" to "Custom..." and put
only "d" or only "Y" or only "H" or only "i" the problem is gone

**Comment by demonlibra** [comment]
Resolved the problem by this way.
In file .../ext/blitze/sitemaker/styles/prosilver/template/blocks/forum_topics.html
changed line
`<p class="small"><i class="fa fa-clock-o"></i>{{ topicrow.TOPIC_POST_TIME|date("M d, Y") }}</p>`
to
`<p class="small"><i class="fa fa-clock-o"></i>{{ topicrow.TOPIC_POST_TIME }}</p>`

**Comment by blitze** [comment]
Thanks for reporting this issue. It had to do with the fact that the date filter in twig expects a string that is supported by the php strtotime function which in turn expects a date in english. On non english boards I was passing in a translated date which caused the error.
