### ISSUE TITLE
[3.1.1] double quote duplicated

### ISSUE THREAD

**Issue by flesage-000** [blitze/phpBB-ext-sitemaker#51]
hello,

I'm trying to had an iframe using sitemaker 3.1.1.

Here is the iframe source code :
```html
<div style="width:100%;min-height:260px;"><iframe
src="https://mmorga.org/widgets/guild_event/546/hrz" 
frameborder="0" style="width:100%;height:100%;"></iframe></div>
```

I use this iframe code in a "custom block" (in "source code" mode), it work fine in preview but in prod mode.

i check source code in browser and it appear that my iframe code has some double quote duplicated and some other weird thing.

Here the bugged source code from browser
```html
<div style="“width:" 100%;="" height:="" 225px;”="" data-mce-style="“width:">
	<span style="“width:100%;height:100%;”" data-mce-object="“iframe”" class="“mce-preview-object" mce-object-iframe”="" data-mce-p-frameborder="“0”" data-mce-p-src="“https://mmorga.org/widgets/guild_event/546/hrz”" contenteditable="“false”">
		<iframe src="“https://mmorga.org/widgets/guild_event/546/hrz”" style="“width:100%;height:100%;”" frameborder="“0”"></iframe>
		<span class="“mce-shim”"></span>
	</span>
</div>
```

I tried to :
- Rewrite all double quote
- Rewrite all the iframe
- Remove style attribut to add width and height as attributs
- Change all double quot for single quote

Nothing works :(.

**Comment by blitze** [comment]
Hi flesage-000, I did not test this on v3.1.1 but on v3.2.0 that is pending validation, I was not able to reproduce the problem. So whatever is the cause of the issue, it seems I already resolved it in the upcoming version of this extension.

Thanks

**Comment by flesage-000** [comment]
The issue has been solved by deactivated the "fancypants" option from this plugin => https://github.com/phpBB-Studio/TextFormatter

Thanks :).
