### ISSUE TITLE
[3.2.0] Fatal error: Uncaught ReflectionException

### ISSUE THREAD

**Issue by demonlibra** [blitze/phpBB-ext-sitemaker#52]
Good day.
I try to update "sitemaker" to last version 3.2.0 and get errors:

`Fatal error: Uncaught ReflectionException: Class Urodoz\Truncate\TruncateService does not exist in /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php:931 Stack trace: #0 /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php(931): ReflectionClass->__construct('Urodoz\\Truncate...') #1 /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php(467): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Object(SplObjectStorage), 'truncator') #2 /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php(995): Symfony\Component\DependencyInjection\ContainerBuilder->get('truncator', 1) #3 /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php(992): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Object(SplObjectStorage)) #4 /opt/lampp/htdocs/docs/vendor/ in /opt/lampp/htdocs/docs/vendor/symfony/dependency-injection/ContainerBuilder.php on line 931`

In fresh installation of phpBB get the same errors.

I tried:
Opera and FireFox
lamp and real webserver
phpBB 3.2.7 and 3.2.8
PHP Version 7.1.11 and 7.1.21
MySQL(i) 10.1.28-MariaDB and MySQL(i) 5.6.41-84.1

**Comment by blitze** [comment]
Hi demonlibra, as v3.2.0 had not been released I'm assuming you got it from GitHub. In that case, it does not come with the vendors installed. You will need to run `composer install` from command line to install vendors

Thanks

**Comment by demonlibra** [comment]
Thaks a lot.

Install last version of "SiteMaker 3.2.0" from GitHub

Open terminal on local machine and run:
`cd /opt/lampp/htdocs/docs/ext/blitze/sitemaker
composer install`
Zip folder /ext/blitze/sitemaker

Disable extension "SiteMaker" in Admin panel of live site
Delete folder /ext/blitze/sitemaker
Unpack zip which get from local machine.


Work fine.
