### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by Galixte** [blitze/phpBB-ext-sitemaker#6]
Hi,

do you have a demo website ?

**Comment by blitze** [comment]
Sorry it took a while to reply. I will put up a demo site soon

**Comment by Galixte** [comment]
Thanks !

**Comment by blitze** [comment]
http://www.phpbb-sitemaker.website/demo
username: demo
password: password

**Comment by Galixte** [comment]
Thanks for demo : http://www.phpbb-sitemaker.website :+1:
