### ISSUE TITLE
Something wrong with Menu

### ISSUE THREAD

**Issue by demonlibra** [blitze/phpBB-ext-sitemaker#65]
**SiteMaker 3.2.2**

**Created Menu**
![322_menu_magament](https://user-images.githubusercontent.com/39235959/99625542-8a82c980-2a41-11eb-9928-424b1e4f2564.png)

**Looks like alright with SiteMaker 3.2.2**
![322_index](https://user-images.githubusercontent.com/39235959/99625541-89ea3300-2a41-11eb-8894-20514a02da38.png)
![322_code](https://user-images.githubusercontent.com/39235959/99625540-88b90600-2a41-11eb-8ece-69e1a54aa7ef.png)

**Try to do the same in SiteMaker 3.3.1**

![331_index](https://user-images.githubusercontent.com/39235959/99625545-8bb3f680-2a41-11eb-90cd-d50589fba705.png)
![331_code](https://user-images.githubusercontent.com/39235959/99625543-8b1b6000-2a41-11eb-8d12-fdfb66ae501c.png)

**Menu showing incorrect. There are no `</ul>` after each element of Menu in html code.**

**Comment by demonlibra** [comment]
.../ext/blitze/phpBB-ext-sitemaker-develop/styles/prosilver/template/event/overall_header_headerbar_after.html

![Снимок экрана от 2020-11-19 13-39-15](https://user-images.githubusercontent.com/39235959/99655660-09412c00-2a6d-11eb-95b9-39b756d30208.png)

**Comment by blitze** [comment]
This was staring me right in the face and I missed it. Thanks for reporting it. I Will work on it.

**Comment by demonlibra** [comment]
Resolved in 3.3.2
Thank you.
