### ISSUE TITLE
Migration from Primetime

### ISSUE THREAD

**Issue by Mauron** [blitze/phpBB-ext-sitemaker#7]
Hello @blitze,
Is there a procedure to migrate from previous **Primetime** structure to **Sitemaker**?

**Comment by blitze** [comment]
There currently isn't one but I will work on it

**Comment by blitze** [comment]
Sorry it took so long to get back with you. I have provided migration from primetime. Please let me know if you run into any issues. Your feedback/suggestions are also welcome.

Thanks

**Comment by Mauron** [comment]
Good, I'll give it a try then!

**Comment by Mauron** [comment]
Right: what was the disabling order for extensions?

**Comment by Mauron** [comment]
Ok, here's an error:
```
SQL ERROR [ mysql4 ]

Field 'hide_attr' doesn't have a default value [1364]

SQL

INSERT INTO phpbb_forums (parent_id, forum_type, forum_status, forum_parents, forum_name, forum_link, forum_desc, forum_desc_uid, forum_desc_options, forum_desc_bitfield, forum_rules, forum_rules_uid, forum_rules_options, forum_rules_bitfield, forum_rules_link, forum_image, forum_style, display_subforum_list, display_on_index, forum_topics_per_page, enable_indexing, enable_icons, enable_prune, prune_days, prune_viewed, prune_freq, forum_flags, left_id, right_id) VALUES (0, 0, 0, '', 'phpBB Sitemaker Extensions', '', '', '', 7, '', '', '', 7, '', '', '', 0, 0, 0, 0, 1, 0, 0, 7, 7, 1, 32, 17, 18)
```

**Comment by blitze** [comment]
phpBB3 forum table does not have a 'hide_attr' field. That tells me you are running another extension that modifies the forum table. Can you tell me the extensions that you are running and your version of phpbb? 

Thanks

**Comment by Mauron** [comment]
Here we are:
'''

**Comment by blitze** [comment]
Wow! Don't know half of these extensions. Any how, I'll try to figure it out. 

On side note, I noticed you're using the primetime categories and content extensions. Those will not work without phpBB Primetime. So even after upgrading to sitemaker, leave the primetime extension in place (disabled but not purged) for now. I'll be updating them pretty soon.

**Comment by blitze** [comment]
Ok, it is Quick Title Edition. Let's see if I can fix this.

**Comment by blitze** [comment]
Ok, so here's the deal, the Quick Title Edition extension is adding a "hide_attr" (text) field to the forum table without a default value. My extension cannot provide this value as it has no knowledge of the Quick Title Edition extension. They will need to address this.

They need to use an event to provide a default value for that field otherwise all other extensions that create a forum without going through a form will fail with that error:

I started a topic on this issue here: https://www.phpbb.com/community/viewtopic.php?f=461&t=2345521

**Comment by Mauron** [comment]
Good job!
