### ISSUE TITLE
problem with the dashboard and add menu option

### ISSUE THREAD

**Issue by BogusCurry** [blitze/phpBB-ext-sitemaker#8]
Hello ;D
At first, your plugin is very nice. So now to my problem, I have in the dashboard in my ACP under menu a button with add menu, but I can not use ihm. He makes nothing, is that a bug ? And my dashboard from the plugin show me this
http://bogus.as4u.de/privat/bilder/Bildschirmfoto_2015-12-12_21-19-24.png

Greetings

Bogus

**Comment by blitze** [comment]
Hi,

Go to the General Tab in ACP and purge the cache. That should fix you up. Let me know if it doesn't.

thanks

**Comment by BogusCurry** [comment]
Thats nice, thanks for you support ;D And all good ;D

**Comment by blitze** [comment]
Good to hear. Let me know if you run into any other issues. By the way, I've gotten rid of the dashboard. It was not a fully baked idea.
