### ISSUE TITLE
[Question] How I can reset the startpage ?

### ISSUE THREAD

**Issue by BogusCurry** [blitze/phpBB-ext-sitemaker#9]
Hello ;D
My startpage has change to the galery, now my question how I can back to the forum as my startpage ?

PS: I have the plugin deaktive and the workdata delete

Greetings

Bogus

**Comment by blitze** [comment]
1. Go into Edit mode
2. Navigate to the gallery page that you have set as the start page
2. Click on "Layouts", then "Remove as start page"
